### PR TITLE
switch sell and buy information for bazaar snapshots

### LINKED ISSUE #1067: Switch bazaar buy and sell orders
They are currently displayed the wrong way around.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #1067

### CODE REVIEW

File: components/PriceGraph/BazaarPriceGraph/BazaarSnapshot/BazaarSnapshot.tsx [hunk 1]
```diff
@@ -113,27 +113,27 @@ function BazaarSnapshot(props: Props) {
...
-                    <Card.Body>{getInformationBody(bazaarSnapshot.buyData)}</Card.Body>
+                    <Card.Body>{getInformationBody(bazaarSnapshot.sellData)}</Card.Body>
                 </Card>
                 <Card className={styles.informationField}>
                     <Card.Header>
-                        <Card.Title>Sell information</Card.Title>
+                        <Card.Title>Buy information</Card.Title>
                     </Card.Header>
-                    <Card.Body>{getInformationBody(bazaarSnapshot.sellData)}</Card.Body>
+                    <Card.Body>{getInformationBody(bazaarSnapshot.buyData)}</Card.Body>
```
Comment (Ekwav) [inline components/PriceGraph/BazaarPriceGraph/BazaarSnapshot/BazaarSnapshot.tsx]: please revert this.
The Buy information should be above the sell orders as thats the price you buy at

**Review by Ekwav — CHANGES_REQUESTED** [review]

**Review by Ekwav — APPROVED** [review]
LGTM! :)
