### PR TITLE
fixed bug with the tag property of the blacklisted items

### LINKED ISSUE #593: Blacklist Tag entries are null
I got bug reports from users with `null` on their blacklist multiple times (and empty filters).  
I suspect the item tag gets lost somewhere.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #593

### CODE REVIEW

File: src/components/MainApp/MainApp.tsx [hunk 1]
```diff
@@ -44,6 +45,8 @@ export function MainApp(props: any) {
                 localStorage.setItem("lastReloadTime", new Date().getTime().toString());
             }
         }
+
+        startMigrations();
```
Comment (Ekwav) [inline src/components/MainApp/MainApp.tsx:49]: I think this should not trigger automatically or at least tell the user in a way that he should double check the new blacklist

**Review by Ekwav — CHANGES_REQUESTED** [review]
