### PR TITLE
fixing error with idb-keyval

### LINKED ISSUE #148: Support Firefox
The page should work in firefox as 10% of our users are using Firefox.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #148

### CODE REVIEW

File: src/api/WebsocketHelper.tsx [hunk 1]
```diff
@@ -68,8 +68,9 @@ function initWebsocket(): void {
 
         if (!websocket && (window as any).websocket) {
             websocket = (window as any).websocket;
-            api.setConnectionId();
-            cacheUtils.checkForCacheClear();
+            api.setConnectionId().then(() => {
+                isConnectionIdSet = true;
```
Comment (Ekwav) [inline src/api/WebsocketHelper.tsx:72]: This variable isn't defined

**Review by Ekwav — CHANGES_REQUESTED** [review]

**Review by Ekwav — APPROVED** [review]
