### PR TITLE
fixes

### LINKED ISSUE #81: Click on notification doesn't navigate if any other page is opened
Happens when there is already a tab of https://sky.coflnet.com opened in the browser. Clicks on new notification will only focus this open tab and not navigate to the correct page.

### LINKED ISSUE #133: Fix Premium page
A few bugs were found with the new premium page.
- The default text "you don't have premium" is displayed for premium users until the request is finished. There should be no/neutral text.
- To use premium please login with Google is still displayed when the user is logged in
- The account name and email is sometimes missing

The last two bugs are visible in this screenshot. 

signal-2021-06-02-203738

### LINKED ISSUE #135: send subFlip after setGoogle
The command `subFlip` is sometimes sent before `setGoogle` this leads to an error response that isn't displayed anywhere.
This seems like a race condition and was reproducible when enabling `slow 3G` throttling. 
`subFlip` requires both `setConId` and `setGoogle` to have been executed before.

Websocket log:
```
{"type":"setConId","data":"IjE1MDRjOWExL[redacted]","mId":1} | 89 | 23:39:04.584
{"type":"ok","data":"\"\"","mId":0,"maxAge":0} | 46 | 23:39:06.283
{"type":"subFlip","data":"","mId":2} | 36 | 23:39:06.284
{"type":"ok","data":"\"\"","mId":1,"maxAge":0} | 46 | 23:39:07.694
{"type":"setGoogle","data":"token","mId":3} | 1638 | 23:39:07.697
{"type":"error","data":"{\"Slug\":\"user_not_set\",\"Message\":\"please login first before executing this\"}","mId":2,"maxAge":0} | 129 | 23:39:09.693
{"type":"ok","data":"\"\"","mId":3,"maxAge":0} | 46 | 23:39:12.339
{"type":"premiumExpiration","data":"unnecesary token repeat, doesn't have to be sent","mId":4} | 1646 | 23:39:12.349
{"type":"premiumExpiration","data":"\"2022-0
```

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #133 
fixes #135 
fixes #81

### CODE REVIEW

File: src/components/GoogleSignIn/GoogleSignIn.tsx [hunk 1]
```diff
@@ -11,32 +13,30 @@ function GoogleSignIn(props: Props) {
...
     }, []);
 
     const onLoginSucces = (response: any) => {
         localStorage.setItem("googleId", response.tokenId);
         setGoogleId(response.tokenId);
         api.setGoogle(response.tokenId).then(() => {
+            refreshTokenSetup(response);
             props.onAfterLogin();
         }).catch(() => {
+            toast.error("A Error occoured by trying to sign into google");
```
Comment (Ekwav) [inline src/components/GoogleSignIn/GoogleSignIn.tsx:26]:
```suggestion
            toast.error("An Error occurred while trying to sign in with google");
```

File: src/components/SubscriptionList/SubscriptionList.tsx [hunk 2]
```diff
@@ -49,7 +49,7 @@ function SubscriptionList(props: Props) {
     }
 
     function onLogin() {
-        let googleId = localStorage.getItem('googleId');
+        let googleId = localStorage.getItem('googleId');
```
Comment (Ekwav) [inline src/components/SubscriptionList/SubscriptionList.tsx:52]: remove the unnecessary white space at the end of this line

**Review by Ekwav — CHANGES_REQUESTED** [review]

**Review by Ekwav — APPROVED** [review]
