### PR TITLE
fixed starting bid

### LINKED ISSUE #39: Starting bid is missing from bin auctions
The starting bid isn't displayed in bin auctions.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #39

### CODE REVIEW

File: src/components/AuctionDetails/AuctionDetails.tsx [hunk 1]
```diff
@@ -98,9 +98,9 @@ function AuctionDetails(props: Props) {
     let copyClick = () => {
         setCopyButtonClicked(true);
         window.navigator.clipboard.writeText("/viewauction " + props.auctionUUID);
-        toast.success(<p>Copied ingame link <br/><i>/viewauction {props.auctionUUID}</i></p>)
+        toast.success(<p>Copied ingame link <br /><i>/viewauction {props.auctionUUID}</i></p>)
```
Comment (Ekwav) [inline src/components/AuctionDetails/AuctionDetails.tsx:101]: why is there a new space in here?
