### PR TITLE
fixes

### LINKED ISSUE #255: Make all horizontal lists scrollable
All horizontal list should be scrollable with the mouse wheel.
I already implemented this in the flipper.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #255
fixes navbar style
fixes body styling

### CODE REVIEW

File: src/components/Startpage/Startpage.tsx [hunk 1]
```diff
@@ -230,8 +245,8 @@ function Startpage() {
                     </Card.Header>
                     <Card.Body>
                         <p>
-                            We moved auctions to another server. 
-                            This should increase performance. 
+                            We moved auctions to another server.
+                            This should increase performance.
```
Comment (Ekwav) [inline src/components/Startpage/Startpage.tsx:249]: why has this changed? It is out of date. 
May be changed to `hypixel api is offline`

**Review by Ekwav — CHANGES_REQUESTED** [review]
