### PR TITLE
fix flipper filter timeouts

### LINKED ISSUE #291: Countdown on /flipper is out of sync
The countdown on /flipper starts when the flipper JavaScript is loaded. However the filter features are only enabled once the /flipper was open for 5 min.
The time displayed should not differ from when the checkbox is enabled by more than a second.

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #291

### CODE REVIEW

File: src/components/Flipper/FlipperFilter/FlipperFilter.tsx [hunk 1]
```diff
@@ -3,18 +3,19 @@ import { Form } from 'react-bootstrap';
...
+import { v4 as generateUUID } from 'uuid';
 
 interface Props {
     onChange(filter: FlipperFilter),
     isLoggedIn?: boolean,
     isPremium?: boolean
 }
 
-let FREE_PREMIUM_SPAN = 1000 * 60 * 5;
+let FREE_PREMIUM_SPAN = 1000 * 60 * 0.1;
```
Comment (Ekwav) [inline src/components/Flipper/FlipperFilter/FlipperFilter.tsx:14]: I think you made this by mistake and would yell at me when I merge it

**Review by Ekwav — APPROVED** [review]

File: src/components/Flipper/FlipperFilter/FlipperFilter.tsx (hunk 1 above)
Comment (Flou21) [inline src/components/Flipper/FlipperFilter/FlipperFilter.tsx:14]: const
