### PR TITLE
fixed bazaar price order

### LINKED ISSUE #865: Bazaar alltime graph is displayed in reverse
https://sky.coflnet.com/item/BOOSTER_COOKIE?range=full
https://sky.coflnet.com/api/bazaar/BOOSTER_COOKIE/history

I sampled start and finish and they are switched, yet the dates below the graph are in the right order

### PR DESCRIPTION
**Pull request by matthias-luger**
fixes #865

### CODE REVIEW

File: components/PriceGraph/AuctionHousePriceGraph/AuctionHousePriceGraph.tsx [hunk 1]
```diff
@@ -93,10 +93,9 @@ function AuctionHousePriceGraph(props: Props) {
                     return
                 }
 
+                console.log(prices)
```
Comment (Ekwav) [inline components/PriceGraph/AuctionHousePriceGraph/AuctionHousePriceGraph.tsx]: Please remove

File: components/PriceGraph/BazaarPriceGraph/BazaarPriceGraph.tsx [hunk 2]
```diff
@@ -253,6 +253,7 @@ function BazaarPriceGraph(props: Props) {
     }
 
     function setChartData(prices: BazaarPrice[]) {
+        console.log(prices)
```
Comment (Ekwav) [inline components/PriceGraph/BazaarPriceGraph/BazaarPriceGraph.tsx]: Please remove

**Review by Ekwav — CHANGES_REQUESTED** [review]

**Review by Ekwav — APPROVED** [review]
